# Generated by Django 2.0.6 on 2018-12-17 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181210_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['time_of_create']},
        ),
        migrations.AddField(
            model_name='author',
            name='time_of_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreateTime'),
        ),
    ]
