# Generated by Django 2.1 on 2019-06-23 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181217_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-time_of_create']},
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='time_of_create',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreateTime'),
        ),
    ]
